# Generated by Django 2.0.3 on 2019-12-29 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_price', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner_platter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_from_cart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_order', to='orders.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Order_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasta_name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pizza_type_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad_name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sub_addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_addon_name', models.CharField(max_length=64)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Topping_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topping_type_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='sub',
            name='sub_addon',
            field=models.ManyToManyField(blank=True, related_name='sub_addons', to='orders.Sub_addon'),
        ),
        migrations.AddField(
            model_name='sub',
            name='sub_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_size', to='orders.Size'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_size', to='orders.Size'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_kind', to='orders.Pizza_type'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_kind', to='orders.Topping_type'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='orders.Order_status'),
        ),
        migrations.AddField(
            model_name='dinner_platter',
            name='plate_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plate_size', to='orders.Size'),
        ),
        migrations.AddField(
            model_name='cart',
            name='dinner_platter',
            field=models.ManyToManyField(blank=True, related_name='ordered_dinner_platter', to='orders.Dinner_platter'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pasta',
            field=models.ManyToManyField(blank=True, related_name='ordered_pasta', to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pizza',
            field=models.ManyToManyField(blank=True, related_name='ordered_pizza', to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='cart',
            name='salad',
            field=models.ManyToManyField(blank=True, related_name='ordered_salad', to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_status', to='orders.Cart_status'),
        ),
        migrations.AddField(
            model_name='cart',
            name='sub',
            field=models.ManyToManyField(blank=True, related_name='ordered_sub', to='orders.Sub'),
        ),
    ]
