# Generated by Django 2.0.3 on 2019-12-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191220_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='topping',
            name='pizzas',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Pizza'),
        ),
    ]
