# Generated by Django 2.0.3 on 2019-12-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191220_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topping_type_name', models.CharField(max_length=30)),
            ],
        ),
    ]
