# Generated by Django 2.0.3 on 2020-01-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191230_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='status',
            new_name='cart_status',
        ),
        migrations.RenameField(
            model_name='dinner_platter',
            old_name='price',
            new_name='price_large',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='price',
            new_name='price_large',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='price',
            new_name='price_large',
        ),
        migrations.AddField(
            model_name='dinner_platter',
            name='price_small',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='price_small',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub',
            name='price_small',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='orders.Topping'),
        ),
    ]
