# Generated by Django 2.0.3 on 2019-12-20 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_topping_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topping_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_kind', to='orders.Topping_type'),
        ),
    ]
